FROM agrigorev/zoomcamp-model:mlops-2024-3.10.13-slim

RUN pip install -U pip & pip install pipenv

COPY [ "Pipfile", "Pipfile.lock", "./" ]

RUN pipenv install --system --deploy

RUN pip install numpy==1.21.5 pandas==1.4.2 scikit-learn==1.0.2 pyarrow

COPY [ "homework.py", "homework.py" ]

ENTRYPOINT [ "python", "homework.py" ]